// libs/sdk-angular/src/use-stream.ts
import {
  DestroyRef,
  computed,
  effect,
  inject,
  isSignal,
  signal,
  untracked,
  type Signal,
} from "@angular/core";
import type { BaseMessage } from "@langchain/core/messages";
import type { Client, Interrupt } from "@langchain/langgraph-sdk";
import {
  filterOutHeadlessToolInterrupts,
  flushPendingHeadlessToolInterrupts,
  type AnyHeadlessToolImplementation,
  type OnToolCallback,
} from "@langchain/langgraph-sdk";
import {
  Client as ClientCtor,
  type ClientConfig,
  type ThreadStream,
} from "@langchain/langgraph-sdk/client";
import {
  StreamController,
  type AgentServerAdapter,
  type AgentServerOptions as StreamAgentServerOptions,
  type ChannelRegistry,
  type CustomAdapterOptions as StreamCustomAdapterOptions,
  type InferStateType,
  type InferToolCalls,
  type InferSubagentStates,
  type RootSnapshot,
  type RunCompletedInfo,
  type RunExecutionInfo,
  type StreamSubmitOptions,
  type SubagentDiscoverySnapshot,
  type SubagentMap,
  type SubgraphByNodeMap,
  type SubgraphDiscoverySnapshot,
  type SubgraphMap,
  type UseStreamOptions as StreamUseStreamOptions,
  type WidenUpdateMessages,
} from "@langchain/langgraph-sdk/stream";

type AngularThreadId = string | null | Signal<string | null | undefined>;

export type AgentServerOptions<StateType extends object> =
  StreamAgentServerOptions<StateType, AngularThreadId>;

export type CustomAdapterOptions<StateType extends object> =
  StreamCustomAdapterOptions<StateType, AngularThreadId, string>;

export type UseStreamOptions<
  StateType extends object = Record<string, unknown>,
> = StreamUseStreamOptions<
  StateType,
  AngularThreadId,
  string | undefined,
  string | undefined,
  string
>;

/**
 * Private field on the handle that carries the
 * {@link StreamController} reference. Selector primitives read this
 * to reach the shared {@link ChannelRegistry}. Use the companion
 * `inject*` selectors (`injectMessages`, `injectToolCalls`,
 * `injectValues`, …) instead of reading this directly.
 */
export const STREAM_CONTROLLER: unique symbol = Symbol.for(
  "@langchain/angular/controller"
);

/**
 * Return shape of {@link useStream} — the Angular `StreamApi`.
 *
 * Reactivity primitives follow Angular conventions:
 *
 *  - Data projections are `Signal<T>`; call them as functions in
 *    templates (`stream.messages()`). They are snapshots — never
 *    mutate the returned arrays / maps.
 *  - Imperative methods (`submit` / `stop` / `respond`) are plain
 *    functions. No `WritableSignal`s are exposed on the root handle.
 *  - Identity values captured at construction time (`client`,
 *    `assistantId`) are exposed as plain values; remount the
 *    component to swap them.
 */
export interface UseStreamReturn<
  T = Record<string, unknown>,
  InterruptType = unknown,
  ConfigurableType extends object = Record<string, unknown>,
  StateType extends object = InferStateType<T>,
  SubagentStates = InferSubagentStates<T>,
> {
  // ----- always-on root projections -----
  /**
   * The most recent `values`-channel snapshot emitted at the root
   * namespace — i.e. the thread-level state as the server sees it
   * after each superstep. Updated on every root `values` event, not
   * on token-level deltas: if you render `stream.values().messages`
   * directly you'll see full turns appear at once instead of
   * streaming token-by-token. Use {@link messages} (or
   * `injectMessages`) for the token-streamed view.
   *
   * Equivalent to calling `injectValues(stream)`.
   */
  readonly values: Signal<StateType>;
  /**
   * The root message projection. Assembled from two sources and
   * merged in real time:
   *
   *  1. `messages`-channel deltas — token-level streaming events
   *     (`message-start`, `content-block-delta`, `message-finish`)
   *     emitted by the runtime. These drive live, token-by-token
   *     updates.
   *  2. `values.messages` snapshots — the authoritative ordering
   *     and any messages the agent produces without token streaming
   *     (human turns, tool results, echoes from subagents).
   *
   * If the backend only emits `values` events (no `messages`
   * channel), every message will appear fully-formed on each
   * values update rather than streaming. This is a backend/runtime
   * concern — the Angular layer faithfully renders whatever the
   * server sends.
   *
   * Equivalent to calling `injectMessages(stream)` with no target.
   */
  readonly messages: Signal<BaseMessage[]>;
  /**
   * Root-namespace tool calls assembled from the `tools` channel.
   * Each entry is a fully parsed {@link AssembledToolCall} with
   * name, args, and id — suitable for rendering approval UIs or
   * forwarding to headless tool handlers.
   *
   * When the stream is typed with an agent brand or tool list,
   * entries are narrowed via {@link InferToolCalls}. Equivalent to
   * calling `injectToolCalls(stream)` with no target.
   */
  readonly toolCalls: Signal<InferToolCalls<T>[]>;
  /**
   * All unresolved protocol interrupts observed on the root
   * namespace during the active thread. Populated from lifecycle /
   * input events and seeded on hydration from `thread.getState()`.
   * Cleared optimistically when a new run starts or an interrupt is
   * resolved via {@link respond} / `submit({ command: { resume } })`.
   */
  readonly interrupts: Signal<Interrupt<InterruptType>[]>;
  /**
   * Convenience alias for {@link interrupts}[0] — the primary
   * interrupt most UIs should act on when only one is pending.
   * `undefined` when no interrupt is active.
   */
  readonly interrupt: Signal<Interrupt<InterruptType> | undefined>;
  /**
   * `true` while a run is active or being started on the current
   * thread. Driven by root-namespace lifecycle events (`running` →
   * `true`, terminal phases → `false`). Use this to disable submit
   * buttons and show in-flight spinners.
   */
  readonly isLoading: Signal<boolean>;
  /**
   * `true` while the initial `thread.getState()` hydration for the
   * active thread is in flight. Distinct from {@link isLoading} —
   * thread loading covers the one-time fetch that seeds
   * {@link values} / {@link messages} before any user submit.
   */
  readonly isThreadLoading: Signal<boolean>;
  /**
   * The last error observed on the active run or hydration attempt.
   * `undefined` when no error has occurred. Cleared optimistically
   * when a new {@link submit} starts.
   */
  readonly error: Signal<unknown>;
  /**
   * Id of the thread the controller is bound to. `null` until the
   * first {@link submit} creates or selects a thread (or until an
   * explicit `threadId` option is provided and hydrated).
   */
  readonly threadId: Signal<string | null>;
  /**
   * Promise that settles when the active thread's initial hydration
   * completes. Exposed so SSR/render-before-flush pipelines can
   * `await stream.hydrationPromise()` before serialising. A fresh
   * promise is installed on every `threadId` change.
   */
  readonly hydrationPromise: Signal<Promise<void>>;

  // ----- always-on discovery -----
  /**
   * Subagents discovered on the root run. For DeepAgent-typed
   * streams the key set is narrowed to the subagent names declared
   * on the agent brand (`keyof InferSubagentStates<T>`).
   */
  readonly subagents: Signal<
    ReadonlyMap<
      keyof SubagentStates & string extends never
        ? string
        : keyof SubagentStates & string,
      SubagentDiscoverySnapshot
    >
  >;
  /**
   * Subgraphs discovered on the root run.
   *
   * A namespace is classified as a subgraph iff at least one
   * strictly-deeper namespace has been observed with it as a prefix.
   * This is inferred from the lifecycle event stream — plain function
   * nodes (`orchestrator`, `writer` in the nested-stategraph example)
   * never appear here even though the server emits namespaced
   * lifecycle events for them. Promotion is monotonic and retroactive;
   * an entry appears as soon as the first descendant event lands.
   */
  readonly subgraphs: Signal<ReadonlyMap<string, SubgraphDiscoverySnapshot>>;
  /**
   * Subgraphs indexed by the graph node that produced them
   * (`addNode("visualizer_0", …)`). Each value is an array because
   * parallel fan-outs and loops can spawn multiple invocations of
   * the same node; arrays preserve insertion order. Updates in
   * lock-step with {@link subgraphs}.
   */
  readonly subgraphsByNode: Signal<
    ReadonlyMap<string, readonly SubgraphDiscoverySnapshot[]>
  >;

  // ----- imperatives -----
  /**
   * Dispatch a new run on the bound thread.
   *
   * `input` is typed as `Partial<StateType>` so IDE autocompletion
   * surfaces the state keys declared on the root primitive. Pass
   * `null` (or omit fields) when resuming an interrupt via
   * `options.command.resume` — the server accepts a null payload
   * in that case.
   */
  submit(
    input: WidenUpdateMessages<Partial<StateType>> | null | undefined,
    options?: StreamSubmitOptions<StateType, ConfigurableType>
  ): Promise<void>;
  /**
   * Abort the in-flight run on the current thread without clearing
   * accumulated state. Sets {@link isLoading} to `false` immediately;
   * {@link values} and {@link messages} are preserved.
   */
  stop(): Promise<void>;
  /**
   * Resume a pending protocol interrupt by sending a response payload
   * back to the interrupted namespace.
   *
   * When `target` is omitted, responds to the latest unresolved
   * interrupt in {@link interrupts}. Pass an explicit
   * `{ interruptId, namespace? }` when multiple interrupts are
   * pending or the interrupt lives in a subgraph namespace.
   */
  respond(
    response: unknown,
    target?: { interruptId: string; namespace?: string[] }
  ): Promise<void>;

  // ----- identity -----
  /** LangGraph SDK client used to construct thread streams. */
  readonly client: Client;
  /** Assistant id the thread is bound to for its lifetime. */
  readonly assistantId: string;

  /**
   * Returns the bound {@link ThreadStream}, if one exists (`undefined`
   * until the thread is hydrated or the first submit completes). Prefer
   * the projections and selector primitives for UI work; use this for
   * low-level protocol access (raw subscriptions, state commands, etc.).
   */
  getThread(): ThreadStream | undefined;

  /** @internal Used by selector primitives. */
  readonly [STREAM_CONTROLLER]: StreamController<
    StateType,
    InterruptType,
    ConfigurableType
  >;
}

/**
 * Erased handle useful as a parameter type for helper components that
 * pass a `stream` through to selector primitives without reading
 * `values` directly. Mirrors the React/Vue `AnyStream` alias.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyStream = UseStreamReturn<any, any, any>;

/**
 * Convenience alias — the fully-resolved return type of
 * {@link useStream} for a given source type `T`.
 */
export type StreamApi<
  T = Record<string, unknown>,
  InterruptType = unknown,
  ConfigurableType extends object = Record<string, unknown>,
> = UseStreamReturn<T, InterruptType, ConfigurableType>;

/**
 * React-compatible alias for the fully-resolved stream handle type.
 * Angular docs prefer {@link StreamApi}, but shared libraries can use
 * this name across framework bindings.
 */
export type UseStreamResult<
  T = Record<string, unknown>,
  InterruptType = unknown,
  ConfigurableType extends object = Record<string, unknown>,
> = UseStreamReturn<T, InterruptType, ConfigurableType>;

/**
 * Framework-free factory that constructs a {@link StreamController}
 * and wraps its stores in Angular Signals. Callers must supply the
 * {@link DestroyRef} that owns the controller's lifetime — it's
 * already captured by the public `injectStream` helper.
 *
 * Exported for advanced callers (e.g. testing utilities, custom
 * factories) that prefer to manage injection scope themselves.
 */
export function useStream<
  T = Record<string, unknown>,
  InterruptType = unknown,
  ConfigurableType extends object = Record<string, unknown>,
>(
  options: UseStreamOptions<InferStateType<T>>,
  destroyRef?: DestroyRef
): UseStreamReturn<T, InterruptType, ConfigurableType> {
  type StateType = InferStateType<T>;

  interface OptionsBag {
    assistantId?: string;
    threadId?: string | null | Signal<string | null | undefined>;
    client?: Client;
    apiUrl?: string;
    apiKey?: string;
    callerOptions?: ClientConfig["callerOptions"];
    defaultHeaders?: ClientConfig["defaultHeaders"];
    transport?: "sse" | "websocket" | AgentServerAdapter;
    fetch?: typeof fetch;
    webSocketFactory?: (url: string) => WebSocket;
    onThreadId?: (threadId: string) => void;
    onCreated?: (info: RunExecutionInfo) => void;
    onCompleted?: (info: RunCompletedInfo) => void;
    initialValues?: StateType;
    messagesKey?: string;
    tools?: AnyHeadlessToolImplementation[];
    onTool?: OnToolCallback;
  }
  const asBag = options as OptionsBag;

  const hasCustomAdapter =
    asBag.transport != null && typeof asBag.transport !== "string";
  const transport = asBag.transport;

  const client: Client =
    asBag.client ??
    (new ClientCtor({
      apiUrl: asBag.apiUrl,
      apiKey: asBag.apiKey,
      callerOptions: asBag.callerOptions,
      defaultHeaders: asBag.defaultHeaders,
    }) as unknown as Client);

  // Custom adapters may omit `assistantId`; the controller still
  // requires one so it has something to forward to `threads.stream`.
  const sentinel = "_";
  const assistantId =
    "assistantId" in options ? (options.assistantId ?? sentinel) : sentinel;

  // Normalize threadId input to a signal — callers may pass plain
  // values, nulls, or their own signals.
  const threadIdInput: Signal<string | null> = (() => {
    const raw = asBag.threadId;
    if (isSignal(raw)) {
      return computed(
        () => (raw as Signal<string | null | undefined>)() ?? null
      );
    }
    const initial: string | null = (raw as string | null | undefined) ?? null;
    return signal(initial) as unknown as Signal<string | null>;
  })();

  const controller = new StreamController<
    StateType,
    InterruptType,
    ConfigurableType
  >({
    assistantId,
    // Cast: the runtime `Client` is state-shape agnostic, but the
    // controller declares `client: Client<StateType>` for its own
    // typings. Same cast is applied in the React/Vue bindings.
    client: client as unknown as Client<StateType>,
    threadId: untracked(() => threadIdInput()),
    transport,
    fetch: hasCustomAdapter ? undefined : asBag.fetch,
    webSocketFactory: hasCustomAdapter ? undefined : asBag.webSocketFactory,
    onThreadId: options.onThreadId,
    onCreated: options.onCreated,
    onCompleted: options.onCompleted,
    initialValues: options.initialValues,
    messagesKey: options.messagesKey,
  });

  // Deferred dispose — matches the React `useEffect(() =>
  // controller.activate())` and Vue `onScopeDispose(deactivate)`
  // patterns. HMR / scope-reuse scenarios stay clean because
  // `activate()` cancels the pending dispose if the scope survives.
  const deactivate = controller.activate();
  const ref = destroyRef ?? inject(DestroyRef);
  ref.onDestroy(deactivate);

  // ─── Reactivity bridge: StreamStore → Signal ────────────────────────
  function bindStore<S>(
    subscribe: (listener: () => void) => () => void,
    getSnapshot: () => S
  ): Signal<S> {
    const s = signal<S>(getSnapshot());
    const unsubscribe = subscribe(() => {
      s.set(getSnapshot());
    });
    ref.onDestroy(unsubscribe);
    return computed(() => s());
  }

  const rootSignal = bindStore<RootSnapshot<StateType, InterruptType>>(
    controller.rootStore.subscribe,
    controller.rootStore.getSnapshot
  );
  const subagentSignal = bindStore<SubagentMap>(
    controller.subagentStore.subscribe,
    controller.subagentStore.getSnapshot
  );
  const subgraphSignal = bindStore<SubgraphMap>(
    controller.subgraphStore.subscribe,
    controller.subgraphStore.getSnapshot
  );
  const subgraphByNodeSignal = bindStore<SubgraphByNodeMap>(
    controller.subgraphByNodeStore.subscribe,
    controller.subgraphByNodeStore.getSnapshot
  );

  const values = computed(() => rootSignal().values);
  const messages = computed(() => rootSignal().messages);
  const toolCalls = computed(
    () => rootSignal().toolCalls as InferToolCalls<T>[]
  );
  const interrupts = computed(() =>
    filterOutHeadlessToolInterrupts(rootSignal().interrupts)
  );
  const interrupt = computed(() => interrupts()[0]);
  const isLoading = computed(() => rootSignal().isLoading);
  const isThreadLoading = computed(() => rootSignal().isThreadLoading);
  const error = computed(() => rootSignal().error);
  const threadId = computed(() => rootSignal().threadId);

  // `hydrationPromise` is a property on the controller that gets
  // swapped on every `hydrate()` call. Exposing it as a signal lets
  // templates `await stream.hydrationPromise()` reactively; we
  // refresh the reference when the root store settles a new promise.
  const hydrationPromise = computed(() => {
    rootSignal();
    return controller.hydrationPromise;
  });

  // ─── threadId reactivity ────────────────────────────────────────────
  //
  // Re-hydrate whenever the caller's threadId input changes after
  // construction. The initial hydrate already fired synchronously in
  // the controller constructor, so we compare against the snapshot
  // captured at construction time rather than blindly skipping the
  // first run — in Angular, `@Input()` bindings apply *between*
  // construction and the first effect tick, so the first read can
  // legitimately be a different (updated) value that needs to
  // hydrate.
  const initialThreadId = untracked(() => threadIdInput()) ?? null;
  let lastAppliedThreadId: string | null = initialThreadId;
  effect(() => {
    const next = threadIdInput() ?? null;
    if (next === lastAppliedThreadId) return;
    lastAppliedThreadId = next;
    untracked(() => {
      void controller.hydrate(next);
    });
  });

  // ─── Headless-tool handling ─────────────────────────────────────────
  const tools = options.tools;
  const onTool = options.onTool;
  if (tools?.length) {
    const handledTools = new Set<string>();

    // Clear the dedup set whenever the thread id changes.
    effect(() => {
      threadIdInput();
      untracked(() => handledTools.clear());
    });

    effect(() => {
      const snapshot = rootSignal();
      const bag = snapshot.values as unknown as Record<string, unknown>;
      const protocolInterrupts = snapshot.interrupts as unknown as Interrupt[];
      const valuesInterrupts = Array.isArray(bag?.__interrupt__)
        ? (bag.__interrupt__ as Interrupt[])
        : [];
      const headlessInterrupts =
        protocolInterrupts.length > 0 ? protocolInterrupts : valuesInterrupts;
      if (headlessInterrupts.length === 0) return;
      untracked(() => {
        flushPendingHeadlessToolInterrupts(
          { ...bag, __interrupt__: headlessInterrupts },
          tools,
          handledTools,
          {
            onTool,
            defer: (run) => {
              void Promise.resolve().then(run);
            },
            resumeSubmit: (command) =>
              controller.submit(null, {
                command,
              } as StreamSubmitOptions<StateType, ConfigurableType>),
          }
        );
      });
    });
  }

  const handle: UseStreamReturn<T, InterruptType, ConfigurableType> = {
    values: values as UseStreamReturn<
      T,
      InterruptType,
      ConfigurableType
    >["values"],
    messages,
    toolCalls,
    interrupts,
    interrupt,
    isLoading,
    isThreadLoading,
    error,
    threadId,
    hydrationPromise,
    subagents: subagentSignal as UseStreamReturn<
      T,
      InterruptType,
      ConfigurableType
    >["subagents"],
    subgraphs: subgraphSignal,
    subgraphsByNode: subgraphByNodeSignal,
    submit: (input, submitOptions) => controller.submit(input, submitOptions),
    stop: () => controller.stop(),
    respond: (response, target) => controller.respond(response, target),
    getThread: () => controller.getThread(),
    client,
    assistantId,
    [STREAM_CONTROLLER]: controller,
  };

  return handle;
}

/**
 * Helper used by the selector primitives to reach the underlying
 * {@link ChannelRegistry} from a stream handle. Kept internal —
 * application code should call `injectMessages`, `injectToolCalls`,
 * etc. instead of reading this directly.
 *
 * @internal
 */
export function getRegistry(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  stream: UseStreamReturn<any, any, any>
): ChannelRegistry {
  return stream[STREAM_CONTROLLER].registry;
}

export type { ThreadStream };

// libs/sdk-react/src/stream-experimental/use-stream.ts
/* __LC_ALLOW_ENTRYPOINT_SIDE_EFFECTS__ */

"use client";

import { useEffect, useMemo, useSyncExternalStore } from "react";
import type { BaseMessage } from "@langchain/core/messages";
import type { Client, Interrupt } from "@langchain/langgraph-sdk";
import {
  Client as ClientCtor,
  type ClientConfig,
  type ThreadStream,
} from "@langchain/langgraph-sdk/client";
import {
  StreamController,
  type AssembledToolCall,
  type ChannelRegistry,
  type RootSnapshot,
  type StreamSubmitOptions,
  type SubagentDiscoverySnapshot,
  type SubagentMap,
  type SubgraphByNodeMap,
  type SubgraphDiscoverySnapshot,
  type SubgraphMap,
} from "@langchain/langgraph-sdk/stream";

/**
 * Unwraps a compiled graph type (anything carrying the
 * `~RunOutput` brand from `CompiledGraph`) into its state shape.
 * Any other `object` type is treated as the state itself, so
 * existing `useStreamExperimental<MyState>()` call sites keep
 * resolving to `MyState` without change.
 *
 * @example
 * ```ts
 * const agent = new StateGraph({ messages: MessagesValue }).compile();
 * type State = StateOf<typeof agent>; // { messages: BaseMessage[] }
 * type Plain = StateOf<{ foo: string }>; // { foo: string }
 * ```
 */
export type StateOf<T> = T extends { "~RunOutput": infer S }
  ? S extends object
    ? S
    : Record<string, unknown>
  : T extends object
    ? T
    : Record<string, unknown>;

/**
 * Options accepted by {@link useStreamExperimental}. Framework-
 * agnostic options are re-exported from
 * `@langchain/langgraph-sdk/stream`; React-specific
 * lifecycle callbacks live here.
 */
export interface UseStreamExperimentalOptions<
  StateType extends object = Record<string, unknown>,
> {
  assistantId: string;
  threadId?: string | null;
  client?: Client;
  apiUrl?: string;
  apiKey?: string;
  callerOptions?: ClientConfig["callerOptions"];
  defaultHeaders?: ClientConfig["defaultHeaders"];
  /** v2 transport. Defaults to `"sse"`. */
  transport?: "sse" | "websocket";
  /** Optional `fetch` override forwarded to the SSE transport. */
  fetch?: typeof fetch;
  /** Optional `WebSocket` factory for the WS transport. */
  webSocketFactory?: (url: string) => WebSocket;
  onThreadId?: (threadId: string) => void;
  onCreated?: (meta: { run_id: string; thread_id: string }) => void;
  initialValues?: StateType;
  /** State key holding the message array. Defaults to `"messages"`. */
  messagesKey?: string;
}

/**
 * Private field on the hook return that carries the
 * {@link StreamController} reference. Selector hooks (`useMessages`,
 * `useToolCalls`, …) read this to reach the shared
 * {@link ChannelRegistry}. Typed as a symbol-keyed field to discourage
 * end-user access — use the selector hooks instead.
 *
 * Exported as a unique symbol so type narrowing works across
 * `useMessages(stream, target)` call sites.
 */
export const STREAM_CONTROLLER: unique symbol = Symbol.for(
  "@langchain/react/stream-experimental/controller"
);

export interface UseStreamExperimentalReturn<
  StateType extends object = Record<string, unknown>,
  InterruptType = unknown,
  ConfigurableType extends object = Record<string, unknown>,
> {
  // ----- always-on root projections -----
  /**
   * The most recent `values`-channel snapshot emitted at the root
   * namespace — i.e. the thread-level state as the server sees it
   * after each superstep. Updated on every root `values` event, not
   * on token-level deltas: if you render `values.messages` directly
   * you'll see full turns appear at once instead of streaming
   * token-by-token. Use {@link messages} (or `useMessages`) for the
   * token-streamed view.
   *
   * Equivalent to calling `useValues(stream)`.
   */
  readonly values: StateType;
  /**
   * The root message projection. Assembled from two sources and
   * merged in real time:
   *
   *  1. `messages`-channel deltas — token-level streaming events
   *     (`message-start`, `content-block-delta`, `message-finish`)
   *     emitted by the runtime. These drive live, token-by-token
   *     updates.
   *  2. `values.messages` snapshots — the authoritative ordering
   *     and any messages the agent produces without token streaming
   *     (human turns, tool results, echoes from subagents).
   *
   * If the backend only emits `values` events (no `messages`
   * channel), every message will appear fully-formed on each
   * values update rather than streaming. This is a backend/runtime
   * concern — the React layer faithfully renders whatever the
   * server sends.
   *
   * Equivalent to calling `useMessages(stream)` with no target.
   */
  readonly messages: BaseMessage[];
  readonly toolCalls: AssembledToolCall[];
  readonly interrupts: Interrupt<InterruptType>[];
  readonly interrupt: Interrupt<InterruptType> | undefined;
  readonly isLoading: boolean;
  readonly isThreadLoading: boolean;
  readonly error: unknown;
  readonly threadId: string | null;

  // ----- always-on discovery -----
  readonly subagents: ReadonlyMap<string, SubagentDiscoverySnapshot>;
  /**
   * Subgraphs discovered on the root run.
   *
   * A namespace is classified as a subgraph iff at least one
   * strictly-deeper namespace has been observed with it as a prefix.
   * This is inferred from the lifecycle event stream — plain function
   * nodes (`orchestrator`, `writer` in the nested-stategraph example)
   * never appear here even though the server emits namespaced
   * lifecycle events for them. Promotion is monotonic and retroactive;
   * an entry appears as soon as the first descendant event lands.
   */
  readonly subgraphs: ReadonlyMap<string, SubgraphDiscoverySnapshot>;
  /**
   * Subgraphs indexed by the graph node that produced them
   * (`addNode("visualizer_0", …)`). Each value is an array because
   * parallel fan-outs and loops can spawn multiple invocations of
   * the same node; arrays preserve insertion order. Updates in
   * lock-step with {@link subgraphs}.
   */
  readonly subgraphsByNode: ReadonlyMap<
    string,
    readonly SubgraphDiscoverySnapshot[]
  >;

  // ----- imperatives -----
  /**
   * Dispatch a new run on the bound thread.
   *
   * `input` is typed as `Partial<StateType>` so IDE autocompletion
   * surfaces the state keys declared on the root hook. Pass `null`
   * (or omit fields) when resuming an interrupt via `options.command.resume`
   * — the server accepts a null payload in that case.
   */
  submit(
    input: Partial<StateType> | null | undefined,
    options?: StreamSubmitOptions<StateType, ConfigurableType>
  ): Promise<void>;
  stop(): Promise<void>;
  respond(
    response: unknown,
    target?: { interruptId: string; namespace?: string[] }
  ): Promise<void>;

  // ----- identity -----
  readonly client: Client;
  readonly assistantId: string;

  /** v2 escape hatch — returns the bound {@link ThreadStream}. */
  getThread(): ThreadStream | undefined;

  /** @internal Used by selector hooks (`useMessages`, `useToolCalls`, …). */
  readonly [STREAM_CONTROLLER]: StreamController<
    StateType,
    InterruptType,
    ConfigurableType
  >;
}

/**
 * Erased stream handle useful as a parameter type for helpers and
 * wrapper components that pass a `stream` through to selector hooks
 * (`useMessages`, `useChannel`, …) without reading `values` directly.
 * Any fully-typed `UseStreamExperimentalReturn<S, I, C>` is
 * assignable to `AnyStream` because the generic slots are `any`
 * (bivariant), which avoids the `CompiledStateGraph` → `Record<string,
 * unknown>` assignment friction you hit when using the bare
 * `UseStreamExperimentalReturn` default.
 *
 * @example
 * ```tsx
 * function SubgraphCard({ stream, subgraph }: {
 *   stream: AnyStream;
 *   subgraph: SubgraphDiscoverySnapshot;
 * }) {
 *   const messages = useMessages(stream, subgraph);
 *   return <Feed messages={messages} />;
 * }
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyStream = UseStreamExperimentalReturn<any, any, any>;

/**
 * React binding for the experimental v2-native stream runtime.
 *
 * `useStreamExperimental` exposes three always-on projections
 * (`values` / `messages` / `toolCalls`) at the thread root plus
 * cheap discovery maps for subagents / subgraphs. Scoped views of
 * subagents, subgraphs, or any namespaced projection are surfaced via
 * the companion selector hooks:
 *
 * ```tsx
 * const stream = useStreamExperimental({ assistantId: "deep-agent" });
 *
 * // Root messages — always on, already class instances.
 * stream.messages.map((m) => <Bubble key={m.id} msg={m} />);
 *
 * // Subagent view — mount = subscribe, unmount = unsubscribe.
 * function SubagentCard({ subagent }) {
 *   const messages = useMessages(stream, subagent);
 *   const toolCalls = useToolCalls(stream, subagent);
 *   return <>{messages.map(...)}</>;
 * }
 * ```
 *
 * The first generic accepts either a plain state type
 * (`useStreamExperimental<MyState>()`) *or* a compiled graph type
 * (`useStreamExperimental<typeof agent>()`); in the latter case the
 * state shape is unwrapped from the graph via {@link StateOf}, so
 * `stream.values` is always typed as the state, never as the graph
 * class itself.
 *
 * @experimental API is unstable and may change until the v2 protocol
 * is GA on LangGraph Platform.
 */
export function useStreamExperimental<
  T extends object = Record<string, unknown>,
  InterruptType = unknown,
  ConfigurableType extends object = Record<string, unknown>,
>(
  options: UseStreamExperimentalOptions<StateOf<T>>
): UseStreamExperimentalReturn<StateOf<T>, InterruptType, ConfigurableType> {
  type StateType = StateOf<T>;
  const client = useMemo<Client>(
    () =>
      options.client ??
      (new ClientCtor({
        apiUrl: options.apiUrl,
        apiKey: options.apiKey,
        callerOptions: options.callerOptions,
        defaultHeaders: options.defaultHeaders,
      }) as unknown as Client),
    [
      options.client,
      options.apiUrl,
      options.apiKey,
      options.callerOptions,
      options.defaultHeaders,
    ]
  );

  // Recreate the controller only on assistantId / client change; the
  // ThreadStream is bound to one assistant for its lifetime and we
  // want selector-hook subscriptions to stay stable across renders.
  const controller = useMemo(
    () =>
      new StreamController<StateType, InterruptType, ConfigurableType>({
        assistantId: options.assistantId,
        // Cast: the runtime `Client` is state-shape agnostic, but the
        // controller declares `client: Client<StateType>` so its own
        // typings line up. Tightening `submit`'s `input` parameter to
        // `Partial<StateType>` surfaced this variance mismatch that
        // was previously masked — the cast is equivalent to the
        // ClientCtor cast above.
        client: client as unknown as Client<StateType>,
        threadId: options.threadId ?? null,
        transport: options.transport,
        fetch: options.fetch,
        webSocketFactory: options.webSocketFactory,
        onThreadId: options.onThreadId,
        onCreated: options.onCreated,
        initialValues: options.initialValues,
        messagesKey: options.messagesKey,
      }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [client, options.assistantId]
  );

  // Rehydrate on threadId change; initial mount uses the id passed to
  // the constructor.
  useEffect(() => {
    void controller.hydrate(options.threadId ?? null);
  }, [controller, options.threadId]);

  // Dispose on unmount / controller swap.
  //
  // We use `controller.activate()` instead of a naive
  // `() => controller.dispose()` cleanup because React 18+
  // `<StrictMode>` in dev mounts → unmounts → remounts components
  // synchronously to surface cleanup bugs. A naive cleanup would
  // permanently tear the controller down on that first synthetic
  // unmount and turn every subsequent `submit()` into a silent
  // no-op. `activate()` defers disposal to the next microtask and
  // cancels it if the effect re-runs — which is exactly the
  // StrictMode remount pattern.
  useEffect(() => controller.activate(), [controller]);

  const root = useSyncExternalStore<RootSnapshot<StateType, InterruptType>>(
    controller.rootStore.subscribe,
    controller.rootStore.getSnapshot,
    controller.rootStore.getSnapshot
  );
  const subagents = useSyncExternalStore<SubagentMap>(
    controller.subagentStore.subscribe,
    controller.subagentStore.getSnapshot,
    controller.subagentStore.getSnapshot
  );
  const subgraphs = useSyncExternalStore<SubgraphMap>(
    controller.subgraphStore.subscribe,
    controller.subgraphStore.getSnapshot,
    controller.subgraphStore.getSnapshot
  );
  const subgraphsByNode = useSyncExternalStore<SubgraphByNodeMap>(
    controller.subgraphByNodeStore.subscribe,
    controller.subgraphByNodeStore.getSnapshot,
    controller.subgraphByNodeStore.getSnapshot
  );

  return useMemo<
    UseStreamExperimentalReturn<StateType, InterruptType, ConfigurableType>
  >(
    () => ({
      values: root.values,
      messages: root.messages,
      toolCalls: root.toolCalls,
      interrupts: root.interrupts,
      interrupt: root.interrupt,
      isLoading: root.isLoading,
      isThreadLoading: root.isThreadLoading,
      error: root.error,
      threadId: root.threadId,
      subagents,
      subgraphs,
      subgraphsByNode,
      submit: (input, submitOptions) => controller.submit(input, submitOptions),
      stop: () => controller.stop(),
      respond: (response, target) => controller.respond(response, target),
      getThread: () => controller.getThread(),
      client,
      assistantId: options.assistantId,
      [STREAM_CONTROLLER]: controller,
    }),
    [
      root,
      subagents,
      subgraphs,
      subgraphsByNode,
      controller,
      client,
      options.assistantId,
    ]
  );
}

/**
 * Helper used by the selector hooks to reach the underlying
 * {@link ChannelRegistry} from a stream handle. Kept internal —
 * application code should call `useMessages`, `useToolCalls`, etc.
 * instead of reading this directly.
 *
 * @internal
 */
export function getRegistry(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  stream: UseStreamExperimentalReturn<any, any, any>
): ChannelRegistry {
  return stream[STREAM_CONTROLLER].registry;
}

export type { ThreadStream };
